name: Portfolio Lint Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run HTML Lint
        run: npx htmlhint src/index.html src/events.html src/clubs.html src/highlights.html src/join.html

      - name: Run JavaScript Lint
        run: npx eslint .